CREATE DATABASE IF NOT EXISTS adstart_db;
USE adstart_db;

CREATE TABLE IF NOT EXISTS forms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phoneNumber VARCHAR(50) NOT NULL,
  company VARCHAR(255) NOT NULL,
  choices TEXT NOT NULL,
  other TEXT,
  budget VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
